### ISSUE TITLE
It would be nice to have a stack.yaml in the repo?

### ISSUE THREAD

**Issue by bojle** [ymherklotz/verismith#103]
I just got done building the project with stack after battling with cabal not being
able to build it because of ghc version discrepancies. To build with stack, I had to
make stack.yaml myself. This involved `stack init` followed by adding packages to `extra-deps` per stack's suggestions. Eventually, after trial-and-error the package has
been built. I think it would be nice if the build process was simply `git clone` and `stack build`. Would be much more convenient.

If you wish, I can learn stack and create a PR adding stack.yaml.

**Comment by mattyoung101** [comment]
Hi, I'm also trying to build this package at the moment and was also unable to build it using Cabal. Could you attach the `stack.yaml` file you created? Thanks.

**Comment by ymherklotz** [comment]
It should work if the version of GHC is the one which is mentioned in the README, i.e. GHC 9.6.4.  I'll add the specific commands to the README to make it more clear.

1. [Install ghcup](https://www.haskell.org/ghcup/install/) to setup the GHC toolchain.
2. Setup cabal 3.12.1.0 and GHC 9.6.4.
3. Build verismith using cabal.

```
ghcup install ghc --set 9.6.4
ghcup install cabal --set 3.12.1.0
cabal update
cabal build
```

Let me know if the above does not work.

Now that cabal-install supports sand-boxed builds, I see less of a need for `stack`.  In addition to that, there are a few packages that we rely on that on not present in the `stackage` snapshots, meaning they would have to be managed manually any ways (`tomland`, `fgl`), so you get less benefit from relying on the snapshots.

Finally, for really precise package management of dependencies we use `nix` directly, that way you get a complete environment that will always be able to build verismith.  If supporting stack is as simple as adding a `stack.yaml` file with the GHC version required I could do that, but it would be quite tedious to have to manage a whole separate list of dependencies just for `stack`.

**Comment by bojle** [comment]
I tried this, still running into errors I ran into before. Here's the log:
```
~/dev/verismith-1.0.0.2 $ cabal build
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: verismith-1.0.0.2 (user goal)
[__1] next goal: tomland (dependency of verismith)
[__1] rejecting: tomland-1.3.3.3 (conflict: verismith => tomland>=1.0 && <1.3)
[__1] skipping: tomland-1.3.3.2, tomland-1.3.3.1, tomland-1.3.3.0,
tomland-1.3.2.0, tomland-1.3.1.0, tomland-1.3.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=1.0 && <1.3' from 'verismith')
[__1] trying: tomland-1.2.1.0
[__2] next goal: base (dependency of verismith)
[__2] rejecting: base-4.16.4.0/installed-4.16.4.0 (conflict: tomland =>
base>=4.10 && <4.14)
[__2] skipping: base-4.20.0.1, base-4.20.0.0, base-4.19.1.0, base-4.19.0.0,
base-4.18.2.1, base-4.18.2.0, base-4.18.1.0, base-4.18.0.0, base-4.17.2.1,
base-4.17.2.0, base-4.17.1.0, base-4.17.0.0, base-4.16.4.0, base-4.16.3.0,
base-4.16.2.0, base-4.16.1.0, base-4.16.0.0, base-4.15.1.0, base-4.15.0.0,
base-4.14.3.0, base-4.14.2.0, base-4.14.1.0, base-4.14.0.0 (has the same
characteristics that caused the previous version to fail: excluded by
constraint '>=4.10 && <4.14' from 'tomland')
[__2] rejecting: base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1
(constraint from non-upgradeable package requires installed instance)
[__2] fail (backjumping, conflict set: base, tomland, verismith)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, tomland, verismith
```

**Comment by ymherklotz** [comment]
Ah is this on `master`?  On 1.0.0.2 it will probably build with a different version of GHC, and definitely with `nix`, but I would recommend using `master` as it should be easier to build.

**Comment by bojle** [comment]
It was not with master, I downloaded a zip from [hackage](https://hackage.haskell.org/package/verismith-1.0.0.2/verismith-1.0.0.2.tar.gz). I tried now with master and ghc version 9.6.5. Does now build. Heres the [log](https://pastebin.com/B4CPmyhP). What version of ghc should be used? and how can I know this?

**Comment by ymherklotz** [comment]
Hmm I've never seen those errors, it seems like an issue with your GHC installation because it is saying that files are missing from `base` and it's failing to build a bunch of packages.  Have you tried running `ghc-pkg check`?

Maybe you can try forcing the reinstall of GHC 9.6.4.  

And I will have to try to update the hackage version, it probably uses a very old GHC version.  The version should be mentioned in the README, but I wouldn't try to build 1.0.0.2 before getting master working.

**Comment by ymherklotz** [comment]
How did you install GHC?

**Comment by bojle** [comment]
Through ghcup:
```
ghcup install ghc --set 9.6.4
```

**Comment by ymherklotz** [comment]
In the verismith repository, can you do:

```
ghc --version
cabal --version
```

Can you try `ghcup install ghc --set --force 9.6.4`.

**Comment by bojle** [comment]
Ok, I found the issue. I had a system wide ghc 9.2 installed which was overshadowing ghcup'ed ghc. I simply uninstalled it and it compiles. Thanks!
