### ISSUE TITLE
cabal: Could not resolve dependencies:

### ISSUE THREAD

**Issue by semiwizard** [ymherklotz/verismith#69]
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: verismith-0.6.0.2 (user goal)
next goal: tomland (dependency of verismith-0.6.0.2)
rejecting: tomland-0.4.0, 0.3.1, 0.3, 0.2.1, 0.2.0, 0.1.0, 0.0.0 (conflict:
verismith => tomland>=1.0 && <1.2)
Dependency tree exhaustively searched.

this is because ghc 's version ?

**Comment by ymherklotz** [comment]
Ah yes, currently it can only build with ghc version 8.6.5, but I actually pushed a patch to develop which lets it build for 8.2.2 as well, and that seems to work.

If you have `nix` installed, it might be easier to build the github repo directly by cloning it and running `nix-build`, this should always work.

I will try and release a new version on hackage which can build with ghc 8.2.2 today though.

**Comment by ymherklotz** [comment]
I have also uploaded a new version to hackage, verismith-1.0.0.0.

```
cabal install verismith
```

should now work with ghc > 8.6.5 && < 8.8.2.

**Comment by semiwizard** [comment]
thank you for your help.
