### ISSUE TITLE
License has contradictory wording

### ISSUE THREAD

**Issue by krupan** [ymherklotz/verismith#72]
Near the top of the LICENSE file it says:

"For commercial use you need a Software Usage Agreement from Imperial
College London."

But further down, in the text of the GPL, it says:

"This License explicitly affirms your unlimited permission to run the unmodified Program"

and:

"You may make, run and propagate covered works that you do not
convey, without conditions..."

In other words, the license seems to contradict itself.  Either commercial use is restricted or permission is granted to run the software without any conditions on it's use.  Which is it?

**Comment by ymherklotz** [comment]
Sorry about the contradiction, I think that we need to change the license to a completely custom one to make that clear.

The use of Verismith is limited to noncommercial, personal and educational use, and a Software Usage Agreement from Imperial College London is needed to use it in a commercial setting. I don't think we can therefore use the GPL license at all actually, so I'll change it as soon as possible.

**Comment by ymherklotz** [comment]
We have just updated the license and opted to make it open source without any restrictions using the GPL license.

There is now a closed source version of Verismith with does not have the restrictions of the GPL and can therefore be modified freely and kept closed source. This version can be acquired with a software usage agreement with Imperial College London.

Hope that clears up the license ambiguity.

**Comment by krupan** [comment]
Excellent!  Thanks for the clarification and quick fix!
